name: First WF
on: [workflow_dispatch,push]
jobs:
    test1:
        name: Runs on Ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: echo Hello
            - name: Get Repository Code
              uses: actions/checkout@v3
            - name: install dpnds
              run: npm ci
            - name: install SDK
              run: npm install @tpio/javascript-opensdk
            - name: test appl
              run: npm run tests
#            - name: test appl
#              run: npm run tests-unit
            
